### PR TITLE
Add a method to set a public-facing message

### PR DESCRIPTION
**Pull request by knpwrs**
The idea here is to provide a consistent key for error messages that are guaranteed to be safe to show to an end user. My use case is a global error handler for a web application that can result in error messages being shown on the screen, but I don't want to show just any message for any error, I want to only show strings that I know are deemed appropriate for end users to see.

### CODE REVIEW

**Comment by samber** [comment]
OMG, you're a genius.

I've seen such a thing in `labstack/echo`, but since I use `gin-gonic/gin`, I always coded workarounds. Embedding it in oops is much better!



In terms of API, I wonder if we should add a getter such as:

```go
func GetPublic(err error, defaultPublicMessage string) string {
    var oopsError oops.OopsError
    if errors.As(err, &oopsError) {
        msg := oopsError.Public()
        if len(msg) > 0 {
            return msg
        }
        return defaultPublicMessage
    }
}
```

**Comment by samber** [comment]
> The idea here is to provide a consistent key 

BTW, the error builder brings a ".Code(string)" method if your error is a key.

**Comment by knpwrs** [comment]
> In terms of API, I wonder if we should add a getter such as:
> 
> ```go
> func GetPublic(err error, defaultPublicMessage string) string {
>     var oopsError oops.OopsError
>     if errors.As(err, &oopsError) {
>         msg := oopsError.Public()
>         if len(msg) > 0 {
>             return msg
>         }
>         return defaultPublicMessage
>     }
> }
> ```

I like that, I'll push it up.

**Comment by knpwrs** [comment]
> BTW, the error builder brings a ".Code(string)" method if your error is a key.

I saw that, but I'm not enterprise enough to define error codes yet 😆

**Comment by samber** [comment]
"work in progress" 🫣

**Review by samber — APPROVED** [review]

**Comment by samber** [comment]
@knpwrs sorry for the late comment: I wonder if we should call this method `.Human(...)` instead ?

**Comment by knpwrs** [comment]
`.Human` is probably good as well. Though I can see `.Public` being used more generically, like for public-facing APIs where the errors are given user-facing strings for masking purposes.

**Comment by samber** [comment]
ok, lets keep public then

**Pull request merged**
